//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAdBook.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfAdBook.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to exit?.
        /// </summary>
        public static string AppExitConfirmationRequst {
            get {
                return ResourceManager.GetString("AppExitConfirmationRequst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdBook.
        /// </summary>
        public static string AppTitleForMessageBox {
            get {
                return ResourceManager.GetString("AppTitleForMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to modify data..
        /// </summary>
        public static string DataModificationError {
            get {
                return ResourceManager.GetString("DataModificationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any attribute.
        /// </summary>
        public static string Filter_AnyAttribute {
            get {
                return ResourceManager.GetString("Filter_AnyAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names: Common name, Given name, Surname, Display name.
        /// </summary>
        public static string Filter_Names {
            get {
                return ResourceManager.GetString("Filter_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phones: Home phone, work phone, mobile phone.
        /// </summary>
        public static string Filter_Phones {
            get {
                return ResourceManager.GetString("Filter_Phones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string LoadFilterControl_AddButton {
            get {
                return ResourceManager.GetString("LoadFilterControl_AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the filtering rules should be met.
        /// </summary>
        public static string LoadFilterControl_AllRules {
            get {
                return ResourceManager.GetString("LoadFilterControl_AllRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one filtering rule should be met.
        /// </summary>
        public static string LoadFilterControl_AnyRule {
            get {
                return ResourceManager.GetString("LoadFilterControl_AnyRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string LoadFilterControl_Filter {
            get {
                return ResourceManager.GetString("LoadFilterControl_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching rule.
        /// </summary>
        public static string LoadFilterControl_MatchingRule {
            get {
                return ResourceManager.GetString("LoadFilterControl_MatchingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string LoadFilterControl_RemoveButton {
            get {
                return ResourceManager.GetString("LoadFilterControl_RemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string LoadFilterControl_Value {
            get {
                return ResourceManager.GetString("LoadFilterControl_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        public static string MainWindow_AboutButton {
            get {
                return ResourceManager.GetString("MainWindow_AboutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string MainWindow_CloseButton {
            get {
                return ResourceManager.GetString("MainWindow_CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit....
        /// </summary>
        public static string MainWindow_EditButton {
            get {
                return ResourceManager.GetString("MainWindow_EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string MainWindow_FilterCaption {
            get {
                return ResourceManager.GetString("MainWindow_FilterCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string MainWindow_LoadButton {
            get {
                return ResourceManager.GetString("MainWindow_LoadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the &apos;Load&apos; button to load contacts..
        /// </summary>
        public static string MainWindow_SearchAdvice1 {
            get {
                return ResourceManager.GetString("MainWindow_SearchAdvice1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this computer is not a member of an Active Directory domain you should setup a connection by clicking the &apos;Settings&apos; button at the bottom of the window..
        /// </summary>
        public static string MainWindow_SearchAdvice2 {
            get {
                return ResourceManager.GetString("MainWindow_SearchAdvice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings....
        /// </summary>
        public static string MainWindow_SettingsButton {
            get {
                return ResourceManager.GetString("MainWindow_SettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string MainWindow_StopButton {
            get {
                return ResourceManager.GetString("MainWindow_StopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begins with.
        /// </summary>
        public static string MatchingRule_BeginsWith {
            get {
                return ResourceManager.GetString("MatchingRule_BeginsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contains.
        /// </summary>
        public static string MatchingRule_Contains {
            get {
                return ResourceManager.GetString("MatchingRule_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ends with.
        /// </summary>
        public static string MatchingRule_EndsWith {
            get {
                return ResourceManager.GetString("MatchingRule_EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is.
        /// </summary>
        public static string MatchingRule_ExactMatch {
            get {
                return ResourceManager.GetString("MatchingRule_ExactMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MsgBoxCaption_Error {
            get {
                return ResourceManager.GetString("MsgBoxCaption_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string MsgBoxCaption_Success {
            get {
                return ResourceManager.GetString("MsgBoxCaption_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string MsgBoxCaption_Warning {
            get {
                return ResourceManager.GetString("MsgBoxCaption_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        public static string PersonDetailsControl_AttrName {
            get {
                return ResourceManager.GetString("PersonDetailsControl_AttrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string PersonDetailsControl_AttrValue {
            get {
                return ResourceManager.GetString("PersonDetailsControl_AttrValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact&apos;s details.
        /// </summary>
        public static string PersonDetailsControl_Title {
            get {
                return ResourceManager.GetString("PersonDetailsControl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute information.
        /// </summary>
        public static string PersonEditorWindow_AttrInfo {
            get {
                return ResourceManager.GetString("PersonEditorWindow_AttrInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the photo.
        /// </summary>
        public static string PersonEditorWindow_ClearPhoto {
            get {
                return ResourceManager.GetString("PersonEditorWindow_ClearPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a photo....
        /// </summary>
        public static string PersonEditorWindow_SelectPhoto {
            get {
                return ResourceManager.GetString("PersonEditorWindow_SelectPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical details.
        /// </summary>
        public static string PersonEditorWindow_TechDetails {
            get {
                return ResourceManager.GetString("PersonEditorWindow_TechDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property editor.
        /// </summary>
        public static string PersonEditorWindow_Title {
            get {
                return ResourceManager.GetString("PersonEditorWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect. .
        /// </summary>
        public static string RepositoryInaccessibleError {
            get {
                return ResourceManager.GetString("RepositoryInaccessibleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a photo file. The filesize must be smaller than 100Kb!.
        /// </summary>
        public static string SelectPhotoDialogCaption {
            get {
                return ResourceManager.GetString("SelectPhotoDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string SettingsWindow_AuthGrp {
            get {
                return ResourceManager.GetString("SettingsWindow_AuthGrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect the domain you logged on to.
        /// </summary>
        public static string SettingsWindow_ConnectDefault {
            get {
                return ResourceManager.GetString("SettingsWindow_ConnectDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string SettingsWindow_ConnectionGrp {
            get {
                return ResourceManager.GetString("SettingsWindow_ConnectionGrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Connect the following domain:.
        /// </summary>
        public static string SettingsWindow_ConnectTo {
            get {
                return ResourceManager.GetString("SettingsWindow_ConnectTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the current user&apos;s credentials.
        /// </summary>
        public static string SettingsWindow_CurUser {
            get {
                return ResourceManager.GetString("SettingsWindow_CurUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Login:.
        /// </summary>
        public static string SettingsWindow_Login {
            get {
                return ResourceManager.GetString("SettingsWindow_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Password:.
        /// </summary>
        public static string SettingsWindow_Password {
            get {
                return ResourceManager.GetString("SettingsWindow_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string SettingsWindow_TestButton {
            get {
                return ResourceManager.GetString("SettingsWindow_TestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsWindow_Title {
            get {
                return ResourceManager.GetString("SettingsWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the following credentials:.
        /// </summary>
        public static string SettingsWindow_UseSpecCred {
            get {
                return ResourceManager.GetString("SettingsWindow_UseSpecCred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection successful..
        /// </summary>
        public static string TestConnectionSuccessfulMessage {
            get {
                return ResourceManager.GetString("TestConnectionSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect..
        /// </summary>
        public static string TestConnectionUnsuccessfulMessage {
            get {
                return ResourceManager.GetString("TestConnectionUnsuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should provide a value..
        /// </summary>
        public static string YouShouldProvideValue {
            get {
                return ResourceManager.GetString("YouShouldProvideValue", resourceCulture);
            }
        }
    }
}
