//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WfAdBook.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WfAdBook.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any attribute.
        /// </summary>
        internal static string CompositeFilterAnyAttributeDisplayName {
            get {
                return ResourceManager.GetString("CompositeFilterAnyAttributeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect..
        /// </summary>
        internal static string ConnectionFailedMsgBoxTitle {
            get {
                return ResourceManager.GetString("ConnectionFailedMsgBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection succeeded..
        /// </summary>
        internal static string ConnectionSucceededMsgBoxText {
            get {
                return ResourceManager.GetString("ConnectionSucceededMsgBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection succeeded.
        /// </summary>
        internal static string ConnectionSucceededMsgBoxTitle {
            get {
                return ResourceManager.GetString("ConnectionSucceededMsgBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact details.
        /// </summary>
        internal static string ContactDetailsFontEntry {
            get {
                return ResourceManager.GetString("ContactDetailsFontEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact list.
        /// </summary>
        internal static string ContactListFontEntry {
            get {
                return ResourceManager.GetString("ContactListFontEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should specify the domain or domain controler..
        /// </summary>
        internal static string ErrorDcIsEmpty {
            get {
                return ResourceManager.GetString("ErrorDcIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value..
        /// </summary>
        internal static string ErrorInvalidValueMsgBoxText {
            get {
                return ResourceManager.GetString("ErrorInvalidValueMsgBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should enter the username..
        /// </summary>
        internal static string ErrorLoginIsEmpty {
            get {
                return ResourceManager.GetString("ErrorLoginIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorMsgBoxTitle {
            get {
                return ResourceManager.GetString("ErrorMsgBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should enter the password..
        /// </summary>
        internal static string ErrorPasswordIsEmpty {
            get {
                return ResourceManager.GetString("ErrorPasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the settings..
        /// </summary>
        internal static string FailedToLoadSettingsMsgBoxText {
            get {
                return ResourceManager.GetString("FailedToLoadSettingsMsgBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read the file..
        /// </summary>
        internal static string FailedToReadTheFileMsgBoxText {
            get {
                return ResourceManager.GetString("FailedToReadTheFileMsgBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is empty..
        /// </summary>
        internal static string FileIsEmptyMsgBoxText {
            get {
                return ResourceManager.GetString("FileIsEmptyMsgBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter list.
        /// </summary>
        internal static string FilterListFontEntry {
            get {
                return ResourceManager.GetString("FilterListFontEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string FindButtonTextBeforeSearch {
            get {
                return ResourceManager.GetString("FindButtonTextBeforeSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string FindButtonTextDuringSearch {
            get {
                return ResourceManager.GetString("FindButtonTextDuringSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A font is not set..
        /// </summary>
        internal static string FontIsNotSetMsg {
            get {
                return ResourceManager.GetString("FontIsNotSetMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begins with.
        /// </summary>
        internal static string LdapMatchingRuleBeginsWithDisplayName {
            get {
                return ResourceManager.GetString("LdapMatchingRuleBeginsWithDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        internal static string LdapMatchingRuleContainsDisplayName {
            get {
                return ResourceManager.GetString("LdapMatchingRuleContainsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends with.
        /// </summary>
        internal static string LdapMatchingRuleEndsWithDisplayName {
            get {
                return ResourceManager.GetString("LdapMatchingRuleEndsWithDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exact match.
        /// </summary>
        internal static string LdapMatchingRuleExactMatchDisplayName {
            get {
                return ResourceManager.GetString("LdapMatchingRuleExactMatchDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file must be less than 100kb..
        /// </summary>
        internal static string PhotoFileIsTooBigMsgBoxText {
            get {
                return ResourceManager.GetString("PhotoFileIsTooBigMsgBoxText", resourceCulture);
            }
        }
    }
}
